"""Lightweight Mermaid syntax validation for ArcForge.

This module performs fast, deterministic checks on raw Mermaid text before any
architecture/content validation runs. It is intentionally conservative: it
flags common formatting problems, but it is not a full Mermaid parser.

The validator focuses on flowchart-style Mermaid because ArcForge generates
architecture diagrams in that format.
"""

from __future__ import annotations

from typing import NotRequired, TypedDict


class SyntaxIssue(TypedDict):
    """A single Mermaid syntax validation issue."""

    rule: str
    message: str


class SyntaxValidationResult(TypedDict):
    """Top-level Mermaid syntax validation response."""

    passed: bool
    errors: list[SyntaxIssue]
    warnings: list[SyntaxIssue]


VALID_DIRECTIONAL_HEADERS = {"TD", "TB", "BT", "LR", "RL"}
VALID_HEADER_PREFIXES = {"graph", "flowchart"}


def _strip_code_fence_lines(lines: list[str]) -> list[str]:
    """Remove optional fenced code block markers from Mermaid snippets."""

    if len(lines) >= 2 and lines[0].strip().startswith("```") and lines[-1].strip().startswith("```"):
        return lines[1:-1]
    return lines


def _first_non_empty_line(lines: list[str]) -> str:
    """Return the first non-empty line, or an empty string if none exists."""

    for line in lines:
        if line.strip():
            return line.strip()
    return ""


def _check_balanced_delimiters(text: str) -> list[str]:
    """Return delimiter errors for unbalanced Mermaid formatting.

    Mermaid labels often use brackets and parentheses, so this check is useful
    for catching broken text generation while staying lightweight.
    """

    errors: list[str] = []
    opening = {"[": "]", "(": ")", "{": "}"}
    closing = {
        "]": "[",
        ")": "(",
        "}": "{",
    }
    stack: list[str] = []
    in_quotes = False

    for char in text:
        if char == '"':
            in_quotes = not in_quotes
            continue

        if in_quotes:
            continue

        if char in opening:
            stack.append(char)
            continue

        if char in closing:
            if not stack or stack[-1] != closing[char]:
                errors.append(f"Unbalanced closing delimiter '{char}'.")
                break
            stack.pop()

    if in_quotes:
        errors.append("Unterminated quoted string.")

    if stack:
        errors.append(f"Unclosed delimiter '{stack[-1]}'.")

    return errors


def _check_header(first_line: str) -> str | None:
    """Validate the required Mermaid header for flowchart diagrams."""

    if not first_line:
        return "Mermaid text is empty."

    parts = first_line.split()
    if len(parts) != 2:
        return "The first Mermaid line must use the form 'graph TD' or 'flowchart LR'."

    header, direction = parts
    if header not in VALID_HEADER_PREFIXES:
        return "Mermaid diagram must start with 'graph' or 'flowchart'."

    if direction not in VALID_DIRECTIONAL_HEADERS:
        return "Mermaid flowchart direction must be one of TD, TB, BT, LR, or RL."

    return None


def validate_mermaid_syntax(mermaid_text: str) -> SyntaxValidationResult:
    """Validate Mermaid text formatting for ArcForge-generated diagrams.

    Args:
        mermaid_text: Raw Mermaid source generated by the LLM.

    Returns:
        A dictionary with:
        - ``passed``: ``True`` when no syntax errors are present.
        - ``errors``: Blocking syntax issues.
        - ``warnings``: Non-blocking style issues.
    """

    errors: list[SyntaxIssue] = []
    warnings: list[SyntaxIssue] = []

    lines = [line.rstrip() for line in mermaid_text.splitlines()]
    lines = _strip_code_fence_lines(lines)
    first_line = _first_non_empty_line(lines)

    header_error = _check_header(first_line)
    if header_error:
        errors.append(
            {
                "rule": "header",
                "message": header_error,
            }
        )

    if not any(line.strip() for line in lines):
        errors.append(
            {
                "rule": "empty",
                "message": "Mermaid text must contain at least one diagram statement.",
            }
        )
    else:
        body_lines = [line for line in lines if line.strip() and line.strip() != first_line]
        if not body_lines:
            warnings.append(
                {
                    "rule": "minimal_diagram",
                    "message": "Mermaid text contains only a diagram header and no diagram content.",
                }
            )

    for delimiter_error in _check_balanced_delimiters(mermaid_text):
        errors.append(
            {
                "rule": "delimiter",
                "message": delimiter_error,
            }
        )

    if "-->" not in mermaid_text and "-.->" not in mermaid_text and "==>" not in mermaid_text and "---" not in mermaid_text:
        warnings.append(
            {
                "rule": "no_edges",
                "message": "Mermaid text does not contain any visible connections between nodes.",
            }
        )

    return {
        "passed": len(errors) == 0,
        "errors": errors,
        "warnings": warnings,
    }
